### PR TITLE
Attempt to fix java tile type bug

### LINKED ISSUE #2128: libtiled-java writeTileSet() didn't write Tile.type attribute
version 1.0.2

### PR DESCRIPTION
**Pull request by Phlosioneer**
This code *should* work, but I'm unable to compile & test it with my
setup. I don't understand how jaxb is setup. The main possible failure
is if the .getTile() function isn't actually generated by jaxb.

Closes #2128 if merged.

### CODE REVIEW

File: util/java/libtiled-java/src/main/java/org/mapeditor/io/TMXMapWriter.java [hunk 1]
```diff
@@ -527,6 +535,10 @@ private void writeTile(Tile tile, XMLWriter w, String wp) throws IOException {
         w.startElement("tile");
         w.writeAttribute("id", tile.getId());
 
+		if (!tile.getType().isEmpty()) {
+			w.writeAttribute("type", tile.getType());
+		}
```
Comment (bjorn) [inline util/java/libtiled-java/src/main/java/org/mapeditor/io/TMXMapWriter.java]: Please make sure to indent with spaces rather than tabs.

**Comment by bjorn** [comment]
> This code _should_ work, but I'm unable to compile & test it with my
> setup. I don't understand how jaxb is setup.

What error are you getting exactly? I personally am having trouble compiling `libtiled-java` as well, but that's probably because my system has Java 11 so I'm running into #2048.

File: util/java/libtiled-java/src/main/java/org/mapeditor/io/TMXMapWriter.java (hunk 1 above)
Comment (Phlosioneer) [reply util/java/libtiled-java/src/main/java/org/mapeditor/io/TMXMapWriter.java]: Whoops! fixed.
